name: multiome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - python-igraph
  - scanpy=1.11.4
  - muon=0.1.6
  - scvi-tools
  - anndata
  - pytorch
  - seaborn
  - matplotlib
  - numpy
  - pandas
  - jupyterlab
  - pyarrow
  - loompy
  - ipywidgets
  - gimmemotifs
#  - pyscenic
  - pip
  - pip:
      - pyscenic
#      - gimmemotifs
      - pychromvar
      - jupyterlab-quarto

#to install pycistopic
# git clone https://github.com/aertslab/scenicplus.git
# cd scenicplus
# pip install .
#
#
#
